### ISSUE TITLE
Agile Tracking - 08/01 to 16/01

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1050]
This issue will help us track our weekly progress, including various TODOs per capita.
**please reference your expanders issues here**

@OriRoth
  - [x] GUI - text selection
  - [ ] GUI - configuration
  - [x] 1 expander
  - [x] First priority - #364, #889
  - [ ] Follow al personal backlog; close about 3 items / week

@ravivos 
  - [ ] improve system
  - [x] 3 expanders - #1023, #988, (testing #979 left)
  - [x] Follow al personal backlog; close about 3 items / week

@dormaayan 
  - [x] 1 expander left (Done But wait for @mdoron implementation in order to enter the project) - 3 already Done
  - [x] Follow al personal backlog; close about 3 items / week
  - [x] First priority -  Done #903,  #1036, #1013

@tomerdragucki
  - [ ] 3 expanders (1 left) (@tomerdragucki please reference them)
  - [x] 1 tipper
  - [ ] Follow al personal backlog; close about 3 items / week
  - [x] First priority - #731

@yuvalsimon 
  - [x] QA
  - [ ] 2 expanders
  - [x] First priority - #84 
  - [ ] #451 , #910 for next week
  - [ ] Follow al personal backlog; close about 3 items / week

@mdoron 
  - [x] generate naming issue #1044, create wiki page of generating new name
  - [ ] 2 expanders (1 left) (@mdoron please reference the expander issue)
  - [x] First priority - #1047

**Comment by yossigil** [comment]
Folks, I expect  you to do finish these stuff as quickly as possible. We need to finish up the stability issues and the bugs introduced into the spartanizer.

**Comment by yuvalsimon** [comment]
@ravivos @dormaayan @OriRoth @tomerdragucki @mdoron 
I will check today for open issues of bugs that should be done in high priority and assign it for next week. Please when you back to work go to your open issues with _First Priority_ label and finish them first. 
@yossigil If you have some issues you want to be done first tag them here.

**Comment by yuvalsimon** [comment]
I updated the tasks for next week. Tell me if you want to change something or if you want more issues. Close the first priority issues firstly. 
@dormaayan You can give me #1013 if you have too much issues

**Comment by mdoron** [comment]
I fixed it to the new implementation, see the wiki page
