### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1084]
Hey folks :1st_place_medal: 
So as you all know, next week will be the last week of the semester.
From an optimistic kind of view - no more homework submissions.
From a pessimistic kind of view - finals are coming.
But from a realistic kind of view - we have a project to hand in - the Athenizer, so there are some stuff that we should go over and comprehend.

## First things first:
  - [x] finishing all agile missions that will be due by 22.01.2017 (preferably ASAP)
  - [x]  releasing 2.8
  - [x] organizing a final meeting with the stuff in which we will present our work (I will schedule it)
  - [x] making a powerpoint (or any other s.a prezi, etc) presentation (preferably in english) for the final meeting (who wants to take care of this?)
  - [x] Do we want to present our project in the projects fair? (I think we should)

With that said, I want to wish, with all my heart, the best of luck to all and may the odds be ever in your favor
https://www.youtube.com/watch?v=_s7qgNMqDJI

**Comment by ravivos** [comment]
No one volunteered for the presentation making, therefore I chose the ones with the least open issues in both 2.8 and 2,8-sprint together (I think that sounds very fair)
@mdoron and @tomerdragucki 
you both have the least so it's on you guys
A different Solution I thought about is choosing the person with the least **closed** issues, in this case @mdoron has the least while @tomerdragucki has an advantage of only one on him.
For now you both are responsible for it, good luck

**Comment by OriRoth** [comment]
See 76145334d36cb11f394272b293029d11f8853949. @mdoron do journey yourself or talk to me when you are done with the journey's edit.

**Comment by yossigil** [comment]
💯
