### ISSUE TITLE
Week 1: Group & Personal Tasks

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1152]
# Week 1: Group & Personal Tasks
Hi team 12, this is the first week of the semester, and we are back to business again. 

## Team Meeting Summary
1. For those of us who didn't touch the project in the last two months, the first and second week will be the opportunity to get on the wave again by coding simple stuff.
2. In the bottom line, we understood that we have to clean the 'leftovers' from the last semester as quick as possible. Unfixed simple annoying bugs, blockers, etc.
3. Our goal is to make Athernizer more usable, get it to a stable version, and make it more intuitive to use.
4. Full attendance is required for the success of our team work.
5. Everyone of us, in his weekly report page, will write every end of week what he did this week.

### Group Tasks
- [x] 1. Create an issue named "_Weekly Report: [my_name]_", or rename your Karma page into it.

Also, each team member who is not on vacation (this week: @ravivos & @tomerdragucki) will have 4 personal tasks.

### @OriRoth 
- [X] Purpose 2-3 architecturally changes that we can perform.
  * New GUI: eclipse widget
  * Separate `Rule` from tippers.
- https://github.com/SpartanRefactoring/Spartanizer/issues/169

### @dormaayan 
- [x] 1. #1137 
- [x] 2. #1138
- [x] 3. #1123
- [x] 4. #1013

### @mdoron
- [x] 1. Warm up: write a new tipper (#1150) with Niv.
- [ ] 2. Start working with Yuval on issues and bugs from 2.9.
- [x] 3. #1122
- [x] 4. Find one **bloater** and add usage of the `Example` class.

### @yuvalsimon 
- [x] 1. Run the project again, check if there are new bugs we are facing (there were changes in the project while we were not here).
- [ ] 2. Find simple Tipper and implement it.
- [ ] 3. Fix 2-3 bugs or unclosed issues from 2.9 (it's ok to work with someone on this, particularly @mdoron).
- [x] 4. Find one **bloater** and add usage of the `Example` class.

### @NivShalmon 
- [x] 1. Add suitable icon for your user (best - of your face).
- [x] 2. Warm up: write a new tipper (#1150) with Doron.
- [ ] 3. #1146.
- [x] 4. Find simple Tipper and implement it.(#1125)
- [x] 5. Find one **bloater** and add usage of the `Example` class.

The milestone is until Monday end of day.
Good luck for all of us!

**Comment by OriRoth** [comment]
There is no point for renaming our karma pages if we intend to use this issue. Yossi offered [this](https://github.com/TechnionYP5777/SmartParking/issues/5) style, so we may use it. Starting next week each person will post his own assignment on this issue. Notice everyone can edit each post on this issue, so we should clear irrelevant content and remove stale posts (like this one).

**Comment by OriRoth** [comment]
Please rename your karma pages to *Weekly Log for ____ ____*

**Comment by OriRoth** [comment]
@dormaayan use this format please.
