### ISSUE TITLE
Week 2: Group & Personal Tasks

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#1166]
# Week 2: Group & Personal Tasks
Second week, warm up is over, we are almost in full composition this week, so big decision can be taken. Also our work should be more efficient and faster, and everyone will get more "heavy" tasks.

### Sunday 
We reviewed our tasks for the first stage (until Passover), and our _Week 1_ tasks. Proposed more architectural changes which will be proposed on Monday's meeting (see #1167):
* New GUI: eclipse widget
* Separate Rule from tippers.
* Make Leonidas accessible for users.
* Recreate the Toolbox in a more efficient way.
### Monday
- [ ] Decide our architectural change
- [ ] Understand the "Shipudia" - what went wrong, how we can do better this semester.
- [x] Distribution of tasks for _Week 2_
    - [x] Coding tasks
    - [x] Project management tasks - partial division is already written below.

### @dormaayan 
- [x]  Building 4 bloaters and improve the abstract pattern system on-the-fly (#1005, #975, #971 ,#1091)
- [x] Testing:  How to write tests, run them, etc. What's the expected code coverage and for which packages?
- [x] Improve tests with binding (Continues works)
### @NivShalmon 
- [ ] create wiki - #1194 
- [x] improve robustness of   @@tests (#1172)
- [x] finish #1146 
- [x] finish #1129
### @OriRoth 
- [ ] Architecture: Not the full shpiel yet, but just describe the architectural change.
- [ ] Implementing the example infrastructure in bloaters
### @ravivos 
- [ ] Install Me: Include installation procedure, operation, web instructions, eclipse instructions, whatever is necessary.
- [x]  Coding Standards #1195 - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Coding-Standards)
- [x]  Building 4 bloaters (#882 tipper, #1023 bloater, #974 bloater, methodDecOneParameter abstractPattern) and improve the abstract pattern system on-the-fly
### @yuvalsimon 
- [ ] Wiki - #1192 
- [ ]  Building 4 bloaters (2 new, 2 old) and improve the abstract pattern system on-the-fly

Have a fruitful week.

**Comment by ravivos** [comment]
relevant for #1167

**Comment by yossigil** [comment]
Good job @mdoron on doing this. :100: @AdiOmari 

We now move to the project management view in which it is easier to manage the issues. Managing issue is not easy, and doing it from within an issue does not work.

FYI: @yuvalsimon @ravivos @OriRoth @NivShalmon @dormaayan @tomerdragucki 

@mdoron : please close this issue.

**Comment by yossigil** [comment]
@SpartanRefactoring/zoomers  @orenafek 

FYI ". Managing issue is not easy, and doing it from within an issue does not work."
