### ISSUE TITLE
234311: Assignment 0

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#452]
Adi and Itay: do you have the list? Can you upload it

List of the 12 or so steps for fist assignment

**Comment by idabran** [comment]
Yossi: I'm not sure I understand - do you mean the 'Issue teaching' issue?

**Comment by yossigil** [comment]
I mean the list of 12 tasks we made in our meeting

**Comment by idabran** [comment]
Hi Zvi,
You took the notes in the meeting, can you please send them to us?
Thanks,
Itai.

**Comment by yossigil** [comment]
@yh-github will set a deadline. @AdiOmari: is in charge of details and first submission.

**Comment by zvili** [comment]
This is the list of tasks defined during our meeting:

1.- My first comment on an issue; add emoji.
2.- Create new issue.
3.- Define "presentable" GitHub profile.
4.- Issue pull request to add your entry to contributors.txt file.
5.- Verify profile - Adi
6.- Invite student to join repository - Adi
7.- Student accepts.
8.- Student adds interactively email address
9.- Add :+1: - Adi
10.- Student issues the following command sequence: clone, edit, status, diff, stage, commit, push.
11.- Student creates, installs and verifies ssh public key.
12.- Play game "was Kilroy here ?"
13.- TDD

**Comment by yossigil** [comment]
@AdiOmari : you will be in charge on the first assignment.

**Comment by AdiOmari** [comment]
👍, what steps will be covered by the first assignment?

**Comment by yossigil** [comment]
Up to 12. @orimarco  will go on with TDD.

**Comment by AdiOmari** [comment]
Please read tutorials 0 through V:
- [ ]  Tutorial 0: What's ahead? (#338)
- [ ]  Tutorial I: My first comment on an issue (#326)
- [ ]  Tutorial II: Create my first issue (#328)
- [ ]  Tutorial III: A presentable GitHub profile (#330)
- [ ]  Tutorial IV: Create your own karma page (#479)
- [ ]  Tutorial V: Home Assignment 0 (#367)


Your task now is to add your name to the contributors.txt file in the Spartanizer project via the github website: 
- [ ]  Navigate to https://github.com/SpartanRefactoring/Spartanizer, 
- [ ]  Find “contributors.txt” file, and click on it.
- [ ]  On the upper right corner of the editor, find the pencil icon and click on it to fork the project and edit the file.
- [ ]  Add your name and email address to the list, while keeping it alphabetically sorted.
- [ ]  Scroll down to “Propose file change” section. Add a title and a comment containing a mention of Adi (@AdiOmari). And click on “Propose file change” button.
- [ ]  Then click on “Create pull request” (in the “Comparing changes” page, which you will be redirected to after clicking on “Propose file change”).


We will verify your profile and will review the changes you made to “contributors.txt” to confirm your pull request. 


Once making sure your profile is valid and obeys to the requirements in tutorial III, you will be invited to join the the “Spartanizer” project, you will receive an email with an invitation. Please click “View invitation” and accept it in order to join the project.


Before proceeding to the next step, you should first generate and add an SSH key to your ssh-agent so you do not need to enter your credentials repeatedly. To do so, follow the instructions in the following issue:
- [ ]  Tutorial/Git 3: create my SSH public key and place it in GitHub (#372)


Next, we will exercise some of the basic and most important operations that you need to know in order to use git, open your preferred console and do the following :
- [ ]  Clone the repository: 
git clone https://github.com/SpartanRefactoring/Spartanizer.git
- [ ]  Then type:
 git status
It will print “Your branch is up-to-date with..” or it will update you about new commits the have been pushed to the repository since you cloned it.
- [ ]  Find the “contributors.txt” file, use an editor to add to it a character among :Killroy, Hershel, Joha, Till Eulenspiegel (while keeping it alphabetically sorted).
- [ ]  Run git status again to see that there are changes that need to be committed.
- [ ]  Run git commit -a -m “write a message here”
- [ ]  Run git push


You may face a conflict case, in which you will have the following message printed:
CONFLICT (content): Merge conflict in <fileName>
Automatic merge failed; fix conflicts and then commit the result.
In such case you may do one of the following:
- [ ]  Keep your version, by running:  git checkout --ours
- [ ]  Keep Their version, by running:  git checkout --theirs
- [ ]  Manually resolve conflicts and commit the new version.
