### ISSUE TITLE
Raviv Rachmiel: introduction

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#519]
- [ ]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:

Example | Score | Why?
------- | ------|-----
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | Bad | Anonymous
![image](https://cloud.githubusercontent.com/assets/12775400/19101029/e525d7d8-8acc-11e6-97f1-8bdc0bb9ac4f.png) | OK | Personal trademark
  - **Excellent**: 
- [ ]  Make sure you present yourself by a readable **nick**

Example | Score | Why?
------- | ------|-----
`Moshe Levy II` | Super | Clear identification
`YossiGil` | Excellent | You identify yourself by full name
`IDabran`  | Good | == **I**tai **Dabran**
`yogi` | OK | Well known nick
`j1046`  | Bad | Who the hell are  you?
`zm&4jk` | Worse | Not even pronnounceable
`r2d2`   | Terrible | We are not playing games here
`ghost` | Disaster | Are you a troll or what? 
  - Bad: `j10463` / `r2d2` / `bb8` / `biscuit` / `the destroyer`
  - Ok: `yogi`  (**Yo**ssi **G**il), `idarban` (**I**tai **D**arban)

- [ ]  Describe yourself in the bio page; FYI, here is my description:
![image](https://cloud.githubusercontent.com/assets/12775400/19105201/753bb934-8ae9-11e6-8f63-659f5c14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)
14162e.png)

- [ ]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
![image](https://cloud.githubusercontent.com/assets/12775400/19105155/3554e8cc-8ae9-11e6-8915-a180075388b1.png)

**Comment by kfir-marx** [comment]
sup mate ;)

**Comment by ravivos** [comment]
@yossigil Done 👍

**Comment by yossigil** [comment]
:+1: 
Try to leave your Karma page open, never close this issue...

**Comment by zahimizrahi** [comment]
Wow! this is excellent!  keep up the good work!

**Comment by yossigil** [comment]
1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
:+1:

**Comment by yonilx** [comment]
Nice job, looks like you're not wasting any time aren't you ?
P.S. if you can look at my page I would be delighted :D #563

**Comment by yossigil** [comment]
Feel free to clean some of the junk you copied from the tutorial.
Keep this open.

**Comment by yossigil** [comment]
Assign  yourself

**Comment by AdiOmari** [comment]
Nice job 👍 . I would edit the issues to remove duplication (last todo) and remove examples. Assign yourself (@yossigil the student may need to be invited to the project to do so, which happens only when they do assignment 0).

**Comment by yossigil** [comment]
- change name of issue as per the message sent on Telegram

**Comment by ravivos** [comment]
## Previous weeks work:
The preparation tutorials - #738,#687,#628
The preparation exercise - #807 
finding a new project idea - #847 
making a wiki for useful eclipse tricks - #864 
started working on the for; return gambit issue - #305 
## This week work:
finished and closed the for;return gambit issue - #305 
finished and closed the unused variable to double underscore bug - #466 
started working on the first expander for the Athenaizer - #883

**Comment by yossigil** [comment]
good job so far

**Comment by ravivos** [comment]
week 1 - vacation 🎉

**Comment by ravivos** [comment]
Week 2 report:
- [x]  Coding Standards #1195 - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Coding-Standards)
- [x]  Building 4 bloaters with abstract pattern:

- #882 
- #1023
- #974
- methodDecOneParameter abstractPattern

- [x] management

**Comment by yossigil** [comment]
💯

**Comment by ravivos** [comment]
Week3 report:
- [x]  Continuous Integration Wiki #1194  - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Continuous-Integration)
- [x]  InstallMe Wiki #1193   - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Installation-instructions)
- [x]  Fixing Build Errors Wiki #1236  - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Fixing-Build-Errors---Travis)
- [x]  #1217 
- [x] Adding CodeCov to Travis CI
- [x] cleaning up TODOs
- [x] management

**Comment by OriRoth** [comment]
I thought we stopped reporting on personal issues...

**Comment by ravivos** [comment]
Week 4 report:
- [x]  Finished adding CodeCov to CI  #1237 
- [x]  Java SWT Wiki #1216   - [link to wiki](https://github.com/SpartanRefactoring/Spartanizer/wiki/Java-SWT-For-Eclipse-Plugin-Widgets)
- [X] Started working on #76 
- [x] management

**Comment by ravivos** [comment]
Week 5 report:
- [x] fixing failing tests and **cleaning test run** -   #1300, #1253, #1254, #1293 
- [x]  Widget operation - #1229
- [X] Widget preferences page (a very big and important issue) - #1224
- [x] management
This was a meaningful weak 😄

**Comment by ravivos** [comment]
Week 6 report (the short week - Wednesday to Sunday):
### Main work:
- [X] #1316 
- [X] #1224 
### Minor work:
- [X] #1325
- [X] cleaning up errors, warnings and popping bugs
- [X] Management

**Comment by ravivos** [comment]
Week 7 report (the short week - Wednesday to Sunday):
### Main work:
- [X] kept on working on the preferences page including the storing part - #1316 
- [ ] #1328 
- [ ] #1327 
- [X] #1321 
### Minor work:
- [X] #1335 
- [X] cleaning up errors, warnings and popping bugs
- [X] Management

**Comment by ravivos** [comment]
Week 8 report:
- [X] #1347
- [X] #1349 - main work included adding a new listEditor and connecting it to my overrided OperationListEditor class 
- [X] #1348
- [X] started to work on a new framework for working with the preferences page along with @NivShalmon - #1321
- [X] Management

**Comment by ravivos** [comment]
Week 9 report:

## Main Work:
- [X] #1321 - done
This issue included working on a new serializing and structure for the widget.
Further explanation and implementation details are described in the issue itself.

#Minor Work, but as important:
- [X] #1401 
- [X] #1416 
- [X] #1417 
- [X] #1414

Probably the hardest weeks which included the most work

**Comment by ravivos** [comment]
Week 10:
- [X] #1405 
- [ ] #1402
- [ ] #1403

reminding that this was a short week because of shavout (3 days in total - thursday, sunday , monday)

**Comment by ravivos** [comment]
Week 11:
- [X] fix #1401  
- [x] #1461 
- [x] #1456 
- [X] #1459 
- [X] work on #1415 (almost done)

**Comment by ravivos** [comment]
Week 12:
- [X] finish #1415  
- [x] #1491 
- [x] #1493
- [X] #1483 
- [X] #1428 
- [X] #1492 
- [x] #1494 

tough week

**Comment by ravivos** [comment]
Week 13 report:
Vacation 🎉

Week 13 second part: 
#1532 
#1503 
#1499 worked on but didn't fix completely
#1552 
#1545 
fix bugs which popped before the release
manage all wikis
