### ISSUE TITLE
Agile - tracking

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#969]
This issue will help us track our weekly progress, including various TODOs per capita.

@OriRoth
  - [x] be awsome
  - [x] build system
  - [x] expander ideas
  - [x] expander implementations

@ravivos 
  - [x] build system
  - [x] expander ideas
  - [x] expander implementations (*2* left)

@dormaayan 
  - [x] build system
  - [x] tests mechanism
  - [x] expander ideas
  - [x] expander implementations

@tomerdragucki
  - [x] expander ideas
  - [x] expander implementations

@yuvalsimon 
  - [x] distribute urgent Spartanizer issues
  - [x] expander ideas (*4* left)
  - [x] expander implementations (*2* left)

@mdoron 
  - [x] expander ideas (*4* left)
  - [x] expander implementations (*3* left)

**Comment by OriRoth** [comment]
@dormaayan please remember to update your status on this issue as we agreed. Delete this comment after you're done.

**Comment by yossigil** [comment]
:+1:

**Comment by yuvalsimon** [comment]
Call new test classes Issue# please (and add link to tested expander)

**Comment by ravivos** [comment]
I think that everybody is done and we can send to our client a prototype.
@mdoron - please mark that you are done if so

**Comment by OriRoth** [comment]
This issue will help us track our weekly progress, including various TODOs per capita.

@OriRoth
  - [x] be awsome - continue
  - [ ] zoom text selection
  - [ ] menu options

@ravivos 
  - [ ] rename ¢, $
  - [ ] fix bugs

@dormaayan 
  - [ ] improve testing
  - [ ] fix bugs

@tomerdragucki
  - [ ] expander with binding
  - [ ] fix bugs

@yuvalsimon 
  - [ ] improve testing

@mdoron 
  - [ ] expander with binding
  - [ ] fix bugs

**Comment by OriRoth** [comment]
This issue will help us track our weekly progress, including various TODOs per capita.

@OriRoth
  - [ ] GUI - text selection
  - [ ] GUI - configuration
  - [ ] 1 expander
 
@ravivos 
  - [ ] improve system
  - [ ] 3 expanders - #1023, #988, #979 

@dormaayan 
  - [ ] 4 expanders

@tomerdragucki
  - [ ] 3 expanders
  - [ ] 1 tipper

@yuvalsimon 
  - [ ] QA
  - [ ] 2 expanders
  - [ ] spartanizer

@mdoron 
  - [ ] generate naming issue

**Comment by OriRoth** [comment]
moved to #1050
